ofek/pypinfo

README.rst
pypinfo/cli.py
pypinfo/core.py

I changed the `--json` option to just be a flag to set the output format. Users can still write the data to a file: `pypinfo --json requests pyversion > data.json`. This is more flexible if users want to avoid writing to disk.
`pypinfo --json requests pyversion`
before:
```
[["python_version", "download_count"], ["2.7", "8627477"], ["3.5", "859432"], ["3.4", "523369"], ["3.6", "486931"], ["2.6", "357381"], ["None", "175019"], ["3.3", "38859"], ["3.7", "9676"], ["3.2", "6228"], ["1.17", "647"], ["2.5", "30"], ["2.4", "14"], ["3.1", "5"], ["3.0", "2"]]
```
after:
```
[
{
"download_count": 8627477,
"python_version": "2.7"
},
{
"download_count": 859432,
"python_version": "3.5"
},
{
"download_count": 523369,
"python_version": "3.4"
},
{
"download_count": 486931,
"python_version": "3.6"
},
{ …
```

prettier JSON output

---

README.rst

In some circumstances it appears possible that the `BigQuery` role category will not appear when creating a new project/account/credential. Waiting for some period of time seems to have fixed it in at least one case, so that recommendation is added here.

README.rst: Rec to wait a bit if no BigQuery role

---

pypinfo/cli.py

Previously, the field names passed to `order` had to be those of the actual BigQuery database, and not those displayed with `pypinfo --help`. Now the appropriate field substitution is made when the `order` argument is passed into `build_query`.

Change --order argument parsing to use the fields from FIELD_MAP as named in "pypinfo --help"

---

README.rst
pypinfo/core.py

Replaces and closes #13, same thing but without the option for human-readable, non-JSON output.
```
[hugo:~/github/pypinfo] master ± pypinfo --days 365 "" project
project         download_count
--------------- --------------
simplejson      327946463
six             214930152
python-dateutil 152089489
setuptools      149294971
botocore        146935887
pip             140216305
requests        137229399
pyasn1          134867638
docutils        126916467
jmespath        117212884
awscli          112539772
rsa             106762453
colorama        101860595
pyyaml          100055678
selenium        98418802
futures         92938638
s3transfer      91310210
awscli-cwlogs   66183214
cffi            65383612
pyparsing       63603014
```
```
[hugo:~/github/pypinfo] thousands ± pypinfo --days …
```

Add thousands separator for non-JSON output

---

pypinfo/cli.py
pypinfo/core.py

For https://github.com/ofek/pypinfo/issues/4.
Examples:
```
[hugo:~/github/pypinfo] pip-only-flag(+11/-4)+* 7s ± pypinfo Flask
download_count
--------------
2661234
[hugo:~/github/pypinfo] pip-only-flag(+11/-4)+* 8s ± pypinfo Flask installer
installer_name download_count
-------------- --------------
pip            2575982
setuptools     52362
None           15351
pex            5518
requests       4471
Browser        3707
bandersnatch   2066
devpi          946
Artifactory    322
distribute     282
OS             181
Homebrew       23
conda          23
[hugo:~/github/pypinfo] pip-only-flag(+11/-4)+* 6s ± pypinfo --pip Flask installer
installer_name download_count
-------------- --------------
pip            2575982
[hugo:~/github/pypinfo] pip-only-flag(+11/-4)+* 6s ± pypinfo --pip Flask …
```

Add --pip to only show installs by pip

---

README.rst
pypinfo/cli.py
pypinfo/core.py

Includes https://github.com/ofek/pypinfo/pull/14.
Adds a column showing how much percent this row is of the total of all rows.
For example:
```
[hugo:~/github/pypinfo] add-percent+* 1 ± pypinfo --percent pillow pyversion
python_version percent download_count
-------------- ------- --------------
2.7            63.8%        1,053,131
3.5            12.5%          205,853
3.6            11.4%          188,545
None           7.1%           117,260
3.4            4.8%            78,943
2.6            0.2%             3,679
3.3            0.1%             1,768
3.7            0.1%             1,385
3.2            0.0%               256
1.17           0.0%                75
2.4            0.0%                39
2.1            0.0%                 5
2.5            0.0%                 3 …
```

Add percent column

---

setup.py

Python requires 3.5+

---

pypinfo/core.py

A common use-case for me is using the stats in issues and PRs on GitHub. I've been pasting using code formatting, but it's straightforward to output using [Markdown](https://help.github.com/articles/organizing-information-with-tables/): it looks about the same on the console and much better in GitHub.
Here are examples using `pypinfo --percent --pip -d 1 pypinfo system`.
```
system_name percent download_count
----------- ------- --------------
Linux         50.0%              2
Darwin        25.0%              1
Windows       25.0%              1
```
system_name percent download_count
----------- ------- --------------
Linux         50.0%              2
Darwin        25.0%              1
Windows       25.0%              1
```
| system_name | percent | download_count |
| ----------- | …
```

Output table in Markdown

---

pypinfo/cli.py
pypinfo/core.py
tests/test_core.py

Like https://github.com/ofek/pypinfo/pull/33 but doesn't include Travis CI changes or flake8 stuff.
Simply adding a colon will align columns nicely in Markdown.
See https://help.github.com/articles/organizing-information-with-tables/#formatting-content-within-your-table
Includes a unit test for this option and the default behaviour, which makes things much easier to develop without going over your quota!
As plaintext:
```
| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 2.7            |   59.3% |          3,048 |
| 3.5            |   20.9% |          1,074 |
| 3.6            |   14.3% |            734 |
| 3.4            |    5.4% |            279 |
| 2.6            |    0.1% |              4 |
```
As rendered Markdown:
| python_version | …

Right-align Markdown

---

pypinfo/core.py

As discussed in https://github.com/ofek/pypinfo/pull/41.
```
$ pypinfo --start-date -39 --end-date -9 --percent --pip --json --indent 2 pypinfo pyversion
{
"last_update": "2018-02-09 06:45:58",
"query": {
"bytes_billed": 0,
"bytes_processed": 0,
"cached": true,
"estimated_cost": "0.00"
},
"rows": [
{
"download_count": 78,
"percent": "0.46",
"python_version": "2.7"
},
{
"download_count": 46,
"percent": "0.27",
"python_version": "3.6"
},
{
"download_count": 42,
"percent": "0.25",
"python_version": "3.5"
},
{
"download_count": 4,
"percent": "0.024",
"python_version": "3.4"
}
]
}
```
```
$ pypinfo --start-date -39 --end-date -9 --percent --pip --markdown --indent 2 pypinfo pyversion
Served from cache: True
Data processed: 0.00 B
Data billed: 0.00 B
Estimated cost: $0.00
| python_version | …
```

Add UTC timestamp to JSON

---

README.rst

* `bash` lexer is for Bash source code.
* `console` is for transcripts of Bash interactive sessions.
You want the latter in README.

fix syntax highlighting in README

---

pypinfo/core.py
tests/test_core.py

Resolves #48.
```console
$ pypinfo --start-date -44 --end-date -15 setuptools
Data processed: 6.04 GiB
Data billed: 6.04 GiB
Estimated cost: $0.03
| download_count |
| -------------- |
|      9,572,911 |
$ pypinfo --start-date 2018-04-01 --end-date 2018-04-30 setuptools
Served from cache: True
Data processed: 0.00 B
Data billed: 0.00 B
Estimated cost: $0.00
| download_count |
| -------------- |
|      9,572,911 |
$ pypinfo --start-date -44 --end-date 2018-04-30 setuptools
Served from cache: True
Data processed: 0.00 B
Data billed: 0.00 B
Estimated cost: $0.00
| download_count |
| -------------- |
|      9,572,911 |
$ pypinfo --start-date 2018-04-01 --end-date -15 setuptools
Served from cache: True
Data processed: 0.00 B
Data billed: 0.00 B
Estimated cost: $0.00
| …
```

Allow yyyy-mm-dd dates

---

.gitignore
pypinfo/cli.py

Fixes #46.
`--pip` is now the default behaviour, with a new `--all` to match the old default behaviour.
```console
$ # with --pip
$ pypinfo --pip requests installer
Data processed: 9.01 GiB
Data billed: 9.01 GiB
Estimated cost: $0.05
| installer_name | download_count |
| -------------- | -------------- |
| pip            |      7,454,395 |
$ # with --all
$ pypinfo --all requests installer
Data processed: 9.01 GiB
Data billed: 9.01 GiB
Estimated cost: $0.05
| installer_name | download_count |
| -------------- | -------------- |
| pip            |      7,454,395 |
| setuptools     |        141,246 |
| Browser        |         80,016 |
| pex            |         54,178 |
| None           |         27,808 |
| bandersnatch   |          8,351 | …
```

Add --all option, default to --pip

---

.gitignore

The directory is automatically generated by the tox command.

Add .tox directory to .gitignore

---

pypinfo/cli.py
pypinfo/core.py
tests/test_core.py

Only if:
* not `--json`: we don't want this included in the JSON, 
* and more than one row of numbers: no need if only one row, as a single row already is the total
* and at least two columns: so there's somewhere to put "Total"
```console
$ pypinfo requests
Data processed: 8.64 GiB
Data billed: 8.64 GiB
Estimated cost: $0.05
| download_count |
| -------------- |
|      7,125,849 |
$ pypinfo requests pyversion
Data processed: 12.10 GiB
Data billed: 12.10 GiB
Estimated cost: $0.06
| python_version | download_count |
| -------------- | -------------- |
| 2.7            |      4,482,484 |
| 3.6            |      1,707,002 |
| 3.5            |        507,756 |
| 3.4            |        392,867 |
| 2.6            |         17,939 |
| 3.7 …
```

Add download total

---

.travis.yml

See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

'sudo: true' is no longer needed

---

pypinfo/fields.py

Flake8 has had a new release, with a new check which fails:
```
⌂86% [hugo:~/github/pypinfo] master+ ± flake8 .
./pypinfo/fields.py:12:39: W605 invalid escape sequence '\.'
./pypinfo/fields.py:12:43: W605 invalid escape sequence '\.'
./pypinfo/fields.py:12:47: W605 invalid escape sequence '\.'
./pypinfo/fields.py:15:39: W605 invalid escape sequence '\.'
./pypinfo/fields.py:19:39: W605 invalid escape sequence '\.'
./pypinfo/fields.py:22:55: W605 invalid escape sequence '\.'
./pypinfo/fields.py:22:59: W605 invalid escape sequence '\.'
./pypinfo/fields.py:22:63: W605 invalid escape sequence '\.'
```
This PR includes a fix to mark the strings as raw strings with `r""`.
I've not yet tested this locally as I'm out of BigQuery quota right now, but will do soon.

Fix W605 invalid escape sequence '\.'

---

pypinfo/cli.py

Sometimes I need to check which actual credentials JSON file is being used, or where it is, so I can use another.
It'd be useful to have an option to print it out. This PR adds a `--verbose` option to print debug messages to stderr. At the moment, it only prints the creds file location, and can be used to add other debug messages in the future.
Example output:
```console
$ pypinfo --test --verbose pip file
Credentials location set to "/Users/hugo/bin/data/pypinfo.json".
SELECT
file.filename as file,
COUNT(*) as download_count,
FROM
TABLE_DATE_RANGE(
[the-psf:pypi.downloads],
DATE_ADD(CURRENT_TIMESTAMP(), -31, "day"),
DATE_ADD(CURRENT_TIMESTAMP(), -1, "day")
)
WHERE
file.project = "pip"
AND details.installer.name = "pip"
GROUP BY
file,
ORDER BY
download_count DESC
LIMIT 10
```
On a system …

Add --verbose option to print credentials location

---

.github/workflows/test.yml
.travis.yml
README.rst
setup.py
tox.ini

Also test on Windows, macOS and Ubuntu using GitHub Actions, with Python 3.5-3.7.
For example:
* https://github.com/hugovk/pypinfo/commit/649224f0da089c80f1469bc3d5dc4536f7f09538/checks?check_suite_id=272725104
Python 3.8 isn't yet available on GHA, but it's tested on Travis CI.
* https://travis-ci.org/hugovk/pypinfo/builds/600265624
And update usage in the README.

Add support for Python 3.8

---

pypinfo/cli.py

This should fix #82 (I'm out of quota right now to test that one).
Running against a project that's not found returns an exception:
```console
$ pypinfo dfdjfkfgkf pyversion
Served from cache: True
Data processed: 0.00 B
Data billed: 0.00 B
Estimated cost: $0.00
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/bin/pypinfo", line 11, in <module>
load_entry_point('pypinfo', 'console_scripts', 'pypinfo')()
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File …
```

Stop early if no download data was returned from BigQuery

---

.travis.yml
tox.ini

Python 3.9 is in alpha with official release in October.
---
Move slower PyPy3 to first to make full use of parallel builds and reduce waiting time by about 15s. Not huge, but still :)
https://travis-ci.com/ofek/pypinfo/builds/149097142
https://travis-ci.org/hugovk/pypinfo/builds/650826587

Test Python 3.9-dev and run slower PyPy3 first, to reduce waiting time

---

setup.py
tests/test_db.py

Fixes https://github.com/ofek/pypinfo/issues/88.
tinyrecord does not yet support the breaking changes in the new tinydb v4 release, and it will take some time for support to be added.
* https://tinydb.readthedocs.io/en/latest/changelog.html#v4-0-0-2020-05-02
* https://tinydb.readthedocs.io/en/latest/upgrade.html#upgrade-v4-0
* https://github.com/eugene-eeo/tinyrecord/issues/11
In the meantime, let's pin to `tinydb<4`.
This also adds simple tests for `db.py`, which[ fail without the pin](https://travis-ci.org/github/hugovk/pypinfo/builds/683406460) and [pass with it](https://travis-ci.org/github/hugovk/pypinfo/builds/683407593).

pin tinydb<4, tinyrecord does not yet support tinydb v4

---

tox.ini

Allows passing command line arguments such as -x and others to pytest
through the tox entry point.

Pass tox CLI positional args through to pytest

---

pypinfo/db.py

Per the appdirs documentation, to disable the appauthor parameter,
should pass False, not the empty string. See:
https://github.com/ActiveState/appdirs/blob/1a6a9da317d88497550d9c79a76bf6b819b17593/appdirs.py#L49-L52
https://github.com/ActiveState/appdirs/blob/1a6a9da317d88497550d9c79a76bf6b819b17593/appdirs.py#L82-L85

Correct appdirs.user_data_dir() usage

---

pypinfo/db.py
tests/test_db.py
tox.ini

When Python warnings are enabled, these appear as listed below.
To resolve, close the database after use is complete. To avoid opening
and closing the same database twice, the helper get_credentials_table()
was added.
Warnings are now enabled by tox to help catch earlier in the development
process.
tests/test_db.py::test_get_credentials
.../pypinfo/tests/test_db.py:11: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/pytest-of-jon/pytest-63/test_get_credentials0/db.json' mode='r+' encoding='UTF-8'>
assert db.get_credentials() is None
tests/test_db.py::test_set_credentials
.../pypinfo/pypinfo/db.py:19: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/pytest-of-jon/pytest-63/test_set_credentials0/db.json' mode='r+' encoding='UTF-8'>
exists = get_credentials() …

Clean up ResourceWarning emitted during tests

---

setup.cfg
tests/test_db.py

Tinyrecord 0.2.0 has just been released with support for TinyDB 4.
We can now upgrade both, and set minimum required versions to ensure compatibility.
Re:
* https://github.com/eugene-eeo/tinyrecord/issues/11
* https://github.com/ofek/pypinfo/issues/88
* https://github.com/ofek/pypinfo/pull/89

 Upgrade for TinyDB and Tinyrecord

---

tests/test_core.py
tox.ini

Helps https://github.com/ofek/pypinfo/issues/77.
Also re-order some existing core tests so they're in the same order as the functions they test.
Coverage increases from 78% to 94%.

Add core tests to increase coverage

---

pypinfo/cli.py
pypinfo/fields.py

The `libc-version` field is of interest in [manylinux](https://github.com/pypa/manylinux) support and evolution analysis.
From the following data, we can extrapolate what `manylinux` policies are supported, if support is limited by `glibc` or `pip` version.
sample query:
```
Matt$ pypinfo -d 1 --where 'details.distro.libc.lib = "glibc" AND details.installer.name = "pip" AND details.system.name = "Linux"' "" installer-version cpu libc-version
Served from cache: True
Data processed: 0.00 B
Data billed: 0.00 B
Estimated cost: $0.00
| installer_version | cpu    | libc_version | download_count |
| ----------------- | ------ | ------------ | -------------- |
| 20.2.4            | x86_64 | 2.27         |     21,974,762 |
| 20.2.4            | x86_64 | 2.28         |     21,457,215 |
| 19.0.3 …
```

Add support for libc & libc-version fields

---

.github/workflows/test.yml
.travis.yml
pypinfo/cli.py
pypinfo/core.py
setup.cfg
tox.ini

Python 3.5 went end-of-life on 2020-09-30.
Dropping support will reduce overall testing resources when running the
full test matrix.
This allows adopting f-strings to improve readability when formatting
simple strings.
For a complete list of end-of-life Python branches, see:
https://devguide.python.org/devcycle/#end-of-life-branches

Remove support for end-of-life Python 3.5

---

.github/workflows/test.yml
setup.cfg
tox.ini

The CI is failing on PyPy3: https://github.com/ofek/pypinfo/runs/1385608760
Sub-dependency `google-api-core` depends on `grpcio`.
However, `grpcio` doesn't support PyPy (https://github.com/grpc/grpc/issues/4221) so it's probably easiest just to drop it.

Drop PyPy3: unsupported by dependency's dependency

---

pypinfo/core.py
pypinfo/fields.py
tests/test_core.py

By using the clustered data table, performance if improved because
BigQuery can skip of data that doesn't match the desired project.
Tested locally:
```
$ pypinfo google-cloud-bigquery        Served from cache: False
Data processed: 740.43 MiB
Data billed: 741.00 MiB
Estimated cost: $0.01
| download_count |
| -------------- |
|     10,149,146 |
```
Tested locally with all supported fields:
```
$ pypinfo google-cloud-bigquery project version file pyversion percent3 percent2 impl impl-version openssl date month year country installer installer-version setuptools-version system system-release distro distro-version cpu libc libc-version
Data processed: 4.62 GiB
Data billed: 4.62 GiB
Estimated cost: $0.03
| project               | version | file …
```

perf: use clustered table and standard SQL for lower query costs

---

README.rst
pypinfo/core.py
tests/test_core.py

Docs updated in https://github.com/pypa/packaging.python.org/pull/831
New location for dataset announced here: https://cloud.google.com/blog/products/open-source/supporting-the-python-ecosystem
I've spot-checked a few packages, and historic data has been imported.

update dataset to new Google-hosted location

---

.github/workflows/lint.yml
.pre-commit-config.yaml
README.rst
pypinfo/cli.py

I often get caught out by the lack of `-h` for help, there's only `--help` by default.
According to the docs, here's how to add `-h` as well:
* https://click.palletsprojects.com/en/8.0.x/documentation/#help-parameter-customization
---
Also, I added Black and Flake8 linting to the CI via pre-commit. It does the same stuff as the tox lint.
Demo:
* https://github.com/hugovk/pypinfo/runs/3394133891?check_suite_focus=true

CLI: Add -h as help option

---

pypinfo/db.py
setup.cfg

platformdirs is a better-maintained fork.
https://github.com/ActiveState/appdirs/issues/79

Replace appdirs with platformdirs

---

pypinfo/core.py
setup.cfg
tests/test_core.py

This is the same method used by setuptools and pip. Using the upstream
implementation ensures that pypinfo remains in sync and never drifts
from the reference implementation. The packaging package is likely
already to be instead for one of the many pypa packages.

Replace normalize() with  upstream packaging.utils.canonicalize_name

---

.pre-commit-config.yaml
pypinfo/cli.py
pypinfo/core.py
pypinfo/db.py
pyproject.toml
setup.cfg

Type annotations allow for static type checking to build additional
confidence in the correctness of internal and third party APIs. A type
checker, such as mypy can help discover bugs when adding or refactoring
code.
The package distributes a py.typed file for PEP-561 compliance.
https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

Add type annotations to the project and run mypy on CI

---

pypinfo/cli.py
pypinfo/core.py
setup.cfg

references: #123
So the issue with #123 is funny, I just forgot to bump google-cloud-bigquery minimum version in `setup.cfg`.
Without bumping it to the release they introduced the context manager, it could have gone mostly right, there's tens of versions since then.
Sadly back then, they had `python_requires=">=3.6"` and now they have `python_requires=">=3.6, <3.10"`, so when we install `google-cloud-bigquery` with Python 3.10 it forces pip to crawl back to this old version not enforcing `<3.10`, but not having `__enter__` neither.
I enforced the right version in `setup.cfg` but we may not want to merge this as it makes `pypinfo` uninstallable with 3.10 as there does not exist a `google-cloud-bigquery` recent enough *and* compatible with py310 (the irony).

Fix some ResourceWarnings.

---

README.rst
setup.cfg

Fix https://github.com/ofek/pypinfo/pull/129#issuecomment-961411090.
```console
$ rm -rf dist
$ python -m build
...
Successfully built pypinfo-20.0.0.tar.gz and pypinfo-20.0.0-py3-none-any.whl
$ twine check --strict dist/*
Checking dist/pypinfo-20.0.0-py3-none-any.whl: FAILED
`long_description` has syntax errors in markup and would not be rendered on PyPI.
line 349: Warning: Inline literal start-string without end-string.
warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/pypinfo-20.0.0.tar.gz: FAILED
`long_description` has syntax errors in markup and would not be rendered on PyPI.
line 349: Warning: Inline literal start-string without end-string.
warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```
RST doesn't like …

Fix 'twine check' errors and warnings

---

.github/workflows/deploy.yml

Re: https://github.com/ofek/pypinfo/pull/129#issuecomment-961704127
To deploy to prod PyPI, push a tag, for example:
```sh
git tag 20.0.0
git push --tags
```
(Doesn't deploy to Test PyPI.)
We may need a bit of iteration, but let's see how this works!

Deploy to PyPI for tags

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.pre-commit-config.yaml
README.rst
pypinfo/core.py
setup.cfg
tox.ini

Python 3.6 is EOL and no longer receiving security updates (or any updates) from the core Python team and we can drop it whenever the next release is.
https://endoflife.date/python
---
Also a few other updates:
* Use f-strings
* Update pre-commit
* GHA: Cache pip with https://github.com/actions/setup-python instead of https://github.com/actions/cache, can remove some config
* GHA: Add `workflow_dispatch` to allow triggering builds

Drop support for EOL Python 3.6

---

.github/workflows/deploy.yml

No longer required.
Follow on from https://github.com/ofek/pypinfo/pull/134#issuecomment-1030874715.

CI: Remove redundant 'python setup.py --version'

---

.pre-commit-config.yaml

This updates `black` to a version not using an internal detail of `click` which has been removed and breaks CI lint workflows.

fix: run `pre-commit autoupdate`

---

.pre-commit-config.yaml
pypinfo/core.py

python 3.7+ dict are ordered, keys can be used as an ordered set
Builds on top of #138

Rework fields deduplication

---

pypinfo/core.py
tests/test_core.py

Using `pypinfo numpy` automatically add some `WHERE` clauses to filter on project name and pip installer:
```
WHERE timestamp BETWEEN ...
AND file.project = "numpy"
AND details.installer.name = "pip"
```
However, when adding a `--where` argument, pypinfo would not honor the project name & installer filters.
`pypinfo --where 'file.filename LIKE "%manylinux%"' numpy`:
```
WHERE timestamp BETWEEN ...
AND file.filename LIKE "%manylinux%"
```
Project & installer filtering are now honored when using `--where`.
`pypinfo --where 'file.filename LIKE "%manylinux%"' numpy`:
```
WHERE timestamp BETWEEN ...
AND file.project = "numpy"
AND details.installer.name = "pip"
AND file.filename LIKE "%manylinux%"
```
fix #45

Update `--where` not to discard `project` / `installer` filtering

---

pypinfo/core.py
pypinfo/fields.py
tests/test_core.py

`pypinfo numpy percent3` creates a query with an empty `GROUP BY` clause which results in a BigQuery exception:
`google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword ORDER at [10:1]`
This commit fixes the logic used to conditionally build the `GROUP BY` clause.

Fix query when only aggregate fields are requested

---

pypinfo/cli.py
pypinfo/core.py
tests/test_core.py

I don't feel very strongly about this test but it will allow to reach 100% coverage in `pypinfo/core.py` (together with #140) which will make it easier to see if we have 100% diff coverage when developing other things locally.

Add unit test for `pypinfo.core.parse_query_result`

---

README.rst
pypinfo/core.py
tests/test_core.py

This allows to gather statistics on specific version of a project.
This implements [PEP 440 version matching](https://peps.python.org/pep-0440/#version-matching).
e.g.
With an exact version:
```
pypinfo % pypinfo 'numpy==1.22.4' file
Data processed: 37.83 MiB
Data billed: 38.00 MiB
Estimated cost: $0.01
| file                                                                    | download_count |
| ----------------------------------------------------------------------- | -------------- |
| numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |          9,291 |
| numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   |          2,379 |
| numpy-1.22.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl |            962 |
| …
```

Add support for version matching

---

.pre-commit-config.yaml
tests/test_core.py
tests/test_db.py

Running mypy on test files helps to ensure the tests are representative
by using correct types for APIs. It also could help to expose mistakes
in tests with improper use of values.

Run mypy on all files including tests

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml
tox.ini

Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) and our dependencies are now finally available for 3.11 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
Plus some more config updates.

Add support for Python 3.11

---

README.rst

I think it's more useful for potential users, and existing users, to see the examples in the usage section first, before the installation screenshots.

README: Usage before installation

---

.coveragerc
pypinfo/__main__.py

This allows you to easily specify which interpreter to use:
```sh
pypinfo --percent -d 1 pillow
python -m pypinfo --percent -d 1 pillow
python3.11 -m pypinfo --percent -d 1 pillow
```

Add `__main__.py` to enable `python -m pypinfo`

---

.github/workflows/test.yml
README.md
pypinfo/cli.py
pypinfo/core.py
pypinfo/db.py
pyproject.toml
tests/test_core.py
tox.ini

Add support for the Python 3.13, due out early next month.
* 3.13 was pending support in gprc, just added: https://github.com/grpc/grpc/issues/34922
Drop support for Python 3.8, end of life early next month.

Add support for Python 3.13, drop EOL 3.8

---

.github/workflows/deploy.yml

> We will soon start the deprecation process for Ubuntu 20.04. While the image is being deprecated, you may experience longer queue times during peak usage hours. Deprecation will begin on **2025-02-01** and the image will be fully unsupported by **2025-04-01**.
https://github.com/actions/runner-images/issues/11101
We're using `ubuntu-latest` in the other workflows, let's use that here too.

GitHub Actions: upgrade from deprecated `ubuntu-20.04`

---

.gemini/config.yaml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml
tox.ini

It's almost end-of-life:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0596/
Also bump GitHub Actions and pre-commit.

Drop support for Python 3.9
